from mongoengine import Document, StringField, TextField, DateTimeField, ListField, DictField, IntField
from datetime import datetime

class GeneratedContent(Document):
    """MongoDB collection - AI Generated Quiz Content"""
    user_id = StringField(required=True)  # Reference tới User._id
    content_type = StringField(choices=['QUIZ', 'QUESTION', 'QUIZ_SET'], default='QUIZ')
    title = StringField(required=True)
    description = TextField()
    content = TextField(required=True)  # JSON or text generated by AI
    topic = StringField(max_length=100)
    difficulty = StringField(choices=['EASY', 'MEDIUM', 'HARD'], default='MEDIUM')
    language = StringField(default='vi')
    
    # AI Model info
    model_used = StringField(default='gpt-3.5-turbo')
    prompt = TextField()  # Original prompt used
    
    # Status
    is_published = IntField(default=0)
    is_deleted = IntField(default=0)
    
    created_at = DateTimeField(default=datetime.utcnow)
    updated_at = DateTimeField(default=datetime.utcnow)
    
    meta = {
        'collection': 'generated_content',
        'indexes': [
            'user_id',
            'content_type',
            'created_at',
            'is_published'
        ]
    }
